# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\x05greet\"{\n\x0bInputStatus\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01z\x18\x02 \x01(\x02\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x11\n\tdirection\x18\x04 \x01(\x02\x12\x10\n\x08\x64istance\x18\x05 \x01(\x02\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x14\n\x0c\x64istanceLeft\x18\x07 \x01(\x02\"8\n\x08OutputAI\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x32\x44\n\x07Greeter\x12\x39\n\x12RequestInstruction\x12\x12.greet.InputStatus\x1a\x0f.greet.OutputAIB\x14\xaa\x02\x11GrpcGreeterClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021GrpcGreeterClient'
  _globals['_INPUTSTATUS']._serialized_start=27
  _globals['_INPUTSTATUS']._serialized_end=150
  _globals['_OUTPUTAI']._serialized_start=152
  _globals['_OUTPUTAI']._serialized_end=208
  _globals['_GREETER']._serialized_start=210
  _globals['_GREETER']._serialized_end=278
# @@protoc_insertion_point(module_scope)
